require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

# Common configuration.
AllCops:
  TargetRubyVersion: 3.0.1
  NewCops: enable
  # Include common Ruby source files.
  Include:
    - '**/*.rb'
    - Gemfile
    - Rakefile
  Exclude:
    - vendor/**/*
    - lib/tasks/**/*
    - node_modules/**/*
    - coverage/**/*
    - rubycritic/**/*
    - storage/**/*
    - tmp/**/*
    - log/**/*
    - .git/**/*
    - bin/*
    - script/*
    - config.ru
    - config/**/*
    - db/**/*
    - app/queries/**/*
    - db/schema.rb
